log_format standard '[$time_local] production.INFO: '
                    'Client: $remote_addr - $remote_user $scheme $host "$request" | '
                    'Response: $status $body_bytes_sent "$http_referer" | '
                    '"$http_user_agent" "$http_x_forwarded_for" | '
                    'Request Time: $request_time Upstream Response Time: $upstream_response_time | '
                    'Request ID: $proxy_request_id';

server {
    listen 80;
    server_name localhost;
    error_log  /var/log/nginx/prod.error.log warn;
    access_log /var/log/nginx/prod.access.log standard;
    server_name _;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    client_max_body_size 50M;
    # Thay localhost bằng tên miền của bạn hoặc IP

    set $proxy_request_id $request_id;
    if ($http_x_request_id != '') {
        set $proxy_request_id $http_x_request_id;
    }
    add_header X-REQUEST-ID $proxy_request_id;

    root /var/www/html;  # Thư mục gốc đã mount vào
    index index.php index.html;

    # Drupal yêu cầu chuyển hướng hầu hết request qua index.php nếu không có file tĩnh
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Định nghĩa xử lý file .php qua php-fpm
    location ~ \.php$ {
        proxy_set_header X-Request-ID $proxy_request_id;
        fastcgi_param X-Request-ID $proxy_request_id;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        # Chú ý: "php" này trùng với tên service trong docker-compose
        # cổng mặc định của php-fpm là 9000

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~* \.(google26a9eb3a393a5d70.html)$ {
        root /var/www/html/google26a9eb3a393a5d70.html; # Trong container, file tĩnh sẽ nằm trong thư mục này
        expires max;
        log_not_found off;
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Bật nén gzip (nếu cần)
    gzip on;
    gzip_types text/css application/javascript text/javascript application/json image/svg+xml;
    gzip_proxied any;
    gzip_comp_level 5;
}
